routes/admin.php
<?php

use App\Http\Controllers\Dashboard\{AlbumImageController,
    AlbumsController,
    AudioController,
    CharacterController,
    CityController,
    AuthController,
    ComplainController,
    ContactUsController,
    CountryController,
    DashboardController,
    FaqsController,
    DistrictController,
    MessageController,
    OfferController,
    OrderController,
    PermissionController,
    NotificationController,
    CategoryController,
    ProductController,
    QuestionsController,
    RuleController,
    SingerController,
    Slidecontroller,
    SubcategoriesController,
    RegionController,
    ReportController,
    Settings\SocialMediaController,
    CouponController,
    SubjectController,
    UserController,
    Settings\SettingController,
    Settings\PackageController};

use App\Models\OrderProduct;


Route::group(['as' => 'admin.', 'middleware' => ['admin', 'role.check', 'locale']], function () {

    /** -------------- Home Start --------------- */
    Route::get('/', [
        'uses' => 'App\Http\Controllers\Dashboard\DashboardController@dashboard',
        'as' => 'admin',
        'title' => 'الصفحه الرئيسيه',
        'child' => [
            'admin.admin'
        ]
    ]);
    /** -------------- Home End --------------- */

    /** -------------- Settings Start --------------- */
    Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
        Route::get('/', [
            'uses' => 'App\Http\Controllers\Dashboard\Settings\SettingController@index',
            'as' => 'index',
            'title' => __('dashboard.main.settings'),
            'child' => [
                'admin.settings.index',
                'admin.settings.update',
                'admin.settings.update_profile',
                'admin.settings.update_password',
                'admin.settings.store_social_media',
                'admin.settings.update_social_media',
                'admin.settings.delete_social_media',
                'admin.settings.update_smtp',
                'admin.settings.update_sms',
                'admin.settings.update_fcm',
            ]

        ]);
        Route::post('/update/setting', [SettingController::class, 'update'])->name('update');
        Route::post('/update/profile/{user}', [SettingController::class, 'updateProfile'])->name('update_profile');
        Route::post('/update/password', [SettingController::class, 'updatePassword'])->name('update_password');

        Route::post('/store/social', [SocialMediaController::class, 'store'])->name('store_social_media');
        Route::put('/update/social/{social}', [SocialMediaController::class, 'update'])->name('update_social_media');
        Route::delete('/{social}', [SocialMediaController::class, 'destroy'])->name('delete_social_media');

        Route::post('smtp/update', [PackageController::class, 'smtp'])->name('update_smtp');
        Route::put('packages/update', [PackageController::class, 'updateSms'])->name('update_sms');
        Route::post('fcm/update', [PackageController::class, 'updateFcm'])->name('update_fcm');
    });
    /** -------------- Settings End --------------- */

    /** -------------- Reports Start --------------- */
    Route::group(['prefix' => 'reports'], function () {
        Route::get('/', [
            'uses' => 'App\Http\Controllers\Dashboard\ReportController@index',
            'as' => 'reports.index',
            'title' => 'التقارير',
            'child' => [
                'admin.reports.index',
                'admin.reports.destroy',
                'admin.reports.destroy_selected',
            ]
        ]);

        Route::delete('/{report}', [ReportController::class, 'destroy'])->name('reports.destroy');
        Route::post('/', [ReportController::class, 'destroySelected'])->name('reports.destroy_selected');

    });
    /** -------------- Reports End --------------- */

    /** -------------- inbox-page Start --------------- */
    Route::group(['prefix' => 'inbox-page', 'as' => 'inbox.'], function () {
        Route::get('/', [
            'uses' => 'App\Http\Controllers\Dashboard\ContactUsController@index',
            'as' => 'index',
            'title' => 'البريد الالكتروني',
            'child' => [
                'admin.inbox.index',
                'admin.inbox.show',
                'admin.inbox.destroy',
                'admin.inbox.destroy_selected',
                'admin.inbox.reply_sms_to_single_user',
                'admin.inbox.reply_email_to_single_user',
                'admin.inbox.reply_notification_to_single_user',
            ]
        ]);
        Route::get('show/{contact}', [ContactUsController::class, 'show'])->name('show');
        Route::delete('/{contact}', [ContactUsController::class, 'destroy'])->name('destroy');
        Route::post('/delete-selected', [ContactUsController::class, 'destroySelected'])->name('destroy_selected');


        /** -------------- Reply message to Single User: Start --------------- */
        Route::post('/reply-sms-to-single-inbox', [ContactUsController::class, 'replySmsToSingleUser'])->name('reply_sms_to_single_user');
        Route::post('/reply-email-to-single-inbox', [ContactUsController::class, 'replyEmailToSingleUser'])->name('reply_email_to_single_user');
        Route::post('/reply-notification-to-single-inbox', [ContactUsController::class, 'replyNotificationToSingleUser'])->name('reply_notification_to_single_user');
        /** -------------- Reply message to Single User: End --------------- */
    });
    /** -------------- inbox-page End --------------- */

    /** -------------- complains Start --------------- */
    Route::group(['prefix' => 'complains', 'as' => 'complains.'], function () {
        Route::get('/', [
            'uses' => 'App\Http\Controllers\Dashboard\ComplainController@index',
            'as' => 'index',
            'title' => 'الشكاوي والمقترحات',
            'child' => [
                'admin.complains.index',
                'admin.complains.show',
                'admin.complains.destroy',
                'admin.complains.destroy_selected',
                'admin.complains.change_status',
                'admin.complains.reply_sms_to_single_user',
                'admin.complains.reply_email_to_single_user',
                'admin.complains.reply_notification_to_single_user',
            ]
        ]);
        Route::get('-show/{complain}', [ComplainController::class, 'show'])->name('show');
        Route::delete('/{complain}', [ComplainController::class, 'destroy'])->name('destroy');
        Route::post('/delete-selected-complain', [ComplainController::class, 'destroySelected'])->name('destroy_selected');
        Route::post('/change-status-complain/{complain}', [ComplainController::class, 'changeStatus'])->name('change_status');

        /** -------------- Reply message to Single User: Start --------------- */
        Route::post('/reply-sms-to-single-complain', [ComplainController::class, 'replySmsToSingleUser'])->name('reply_sms_to_single_user');
        Route::post('/reply-email-to-single-complain', [ComplainController::class, 'replyEmailToSingleUser'])->name('reply_email_to_single_user');
        Route::post('/reply-notification-to-single-complain', [ComplainController::class, 'replyNotificationToSingleUser'])->name('reply_notification_to_single_user');
        /** -------------- Reply message to Single User: End --------------- */
    });
    /** -------------- complains End --------------- */



    /** -------------- User Start --------------- */
    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', [
            'uses' => 'App\Http\Controllers\Dashboard\UserController@index',
            'as' => 'index',
            'title' => 'الاعضاء',
            'child' => [
                'admin.users.index',
                'admin.users.blocked',
                'admin.users.active',
                'admin.users.inactive',
                'admin.users.male',
                'admin.users.female',
                'admin.users.create',
                'admin.users.downloadUsers',
                'admin.users.store',
                'admin.users.show',
                'admin.users.edit',
                'admin.users.update',
                'admin.users.destroy',
                'admin.users.destroy_selected',
                'admin.users.block_user',
                'admin.users.un_block_user',
                'admin.notification.create',
                'admin.users.send_sms_to_all',
                'admin.users.send_email_to_all',
                'admin.users.send_notification_to_all',
                'admin.users.send_sms_to_single_user',
                'admin.users.send_email_to_single_user',
                'admin.users.send_notification_to_single_user',
            ]
        ]);
        Route::get('/blocked', [UserController::class, 'blocked'])->name('blocked');
        Route::get('/active', [UserController::class, 'activeUsers'])->name('active');
        Route::get('/inactive', [UserController::class, 'inActiveUsers'])->name('inactive');
        Route::get('/male', [UserController::class, 'maleUsers'])->name('male');
        Route::get('/female', [UserController::class, 'femaleUsers'])->name('female');
        Route::get('/download-users', [UserController::class, 'downloadAllUsers'])->name('downloadUsers');
        Route::get('/create', [UserController::class, 'create'])->name('create');
        Route::post('/', [UserController::class, 'store'])->name('store');
        Route::get('/{user}', [UserController::class, 'show'])->name('show');
        Route::get('/{user}/edit', [UserController::class, 'edit'])->name('edit');
        Route::put('/{user}', [UserController::class, 'update'])->name('update');
        Route::delete('/{user}', [UserController::class, 'destroy'])->name('destroy');
        Route::post('/selected', [UserController::class, 'destroySelected'])->name('destroy_selected');

routes/web.php
<?php

use App\Http\Controllers\Site\AuthController;
use App\Http\Controllers\Site\HomeController;
use App\Http\Controllers\Site\ProductController;
use App\Http\Controllers\Site\SettingController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/dashboard')->name('dashboard')->middleware('admin');

app()->singleton('lang', function () {
    return App\Http\Controllers\Site\LanguageController::lang();
});

Route::get('lang/{lang}', function ($lang) {
    if ($lang == 'ar') {
        session()->put('lang' , 'ar');
    } else {
        session()->put('lang' , 'en');
    }
    if (\Auth::check()) {
        \Auth::user()->lang = $lang;
        \Auth::user()->update();
    }
    return back();
});

Route::group(['middleware' => 'auth'] , function () {


    Route::post('/add-to-cart' , [ProductController::class , 'addCart'])->name('add-to-cart');
    Route::get('/cart', [ProductController::class, 'getCart'])->name('cart');
    Route::get('/bill', [ProductController::class, 'getCheckout'])->name('bill');
    Route::post('/checkout', [ProductController::class, 'Checkout'])->name('checkout');
    Route::get('/reduce/{product}', [ProductController::class, 'getRemoveItem'])->name('reduce');


    Route::get('/likes', [HomeController::class, 'likes'])->name('likes');
    Route::post('/like', [HomeController::class, 'like'])->name('like');
    Route::post('/rate', [HomeController::class, 'rate'])->name('rate');



    Route::get('/change', [AuthController::class, 'change'])->name('change');

    Route::get('/profile' , [AuthController::class , 'profile'])->name('profile');
    Route::post('/storeuser' , [AuthController::class , 'storeuser'])->name('storeuser');
    Route::post('/updatePassword' , [AuthController::class , 'updatePassword'])->name('updatePassword');

});

Route::get('/', [HomeController::class, 'index'])->name('index');

Route::get('/products/{category}', [ProductController::class, 'products'])->name('products');
Route::get('/product/{product}', [ProductController::class, 'product'])->name('product');
Route::post('/filter',[ProductController::class , 'getFilter'])->name('filter');
Route::get('/album/{album}', [ProductController::class, 'album'])->name('album');

Route::get('/questions', [HomeController::class, 'questions'])->name('questions');
Route::post('/storefaqs', [HomeController::class, 'store'])->name('storefaqs');
Route::get('/contact', [SettingController::class, 'contact'])->name('contact');
Route::get('/joinus', [SettingController::class, 'joinus'])->name('joinus');

Route::get('/about', [SettingController::class, 'about'])->name('about');


Route::get('/forget' , [AuthController::class , 'forget'])->name('forget');
Route::post('/forgetData' , [AuthController::class , 'forgetData'])->name('forgetData');
Route::get('/sendcode/{user}' , [AuthController::class , 'sendcode'])->name('sendcode');
Route::post('/send/{user}' , [AuthController::class , 'passwordupdate'])->name('send');

Route::get('/active/{id}' , [AuthController::class , 'active'])->name('confirmation');
Route::post('/activeAccount/{id}' , [AuthController::class , 'activeAccount'])->name('activeAccount');

Route::get('/rules', [HomeController::class, 'rules'])->name('rules');
Route::get('/privacy', [SettingController::class, 'privacy'])->name('privacy');

Route::group(['middleware' =>'guest'] , function (){
Route::get('register' , [AuthController::class , 'register'])->name('register');
Route::post('store' , [AuthController::class , 'store'])->name('storeregister');
Route::get('login', [AuthController::class, 'login'])->name('login');
Route::post('login', [AuthController::class, 'checkLogin'])->name('post.login');
});
Route::get('logout', [AuthController::class, 'logout'])->name('logout');

resources/views/admin/includes/confirm-deletes.blade.php
<script>
    function swal_confirm_delete(url, rowId) {
        Swal.fire({
            title: "{{ __('dashboard.alerts.do_you_want_to_delete_this_row') }}",
            // text: "You won't be able to revert this!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: "{{ __('dashboard.action.yes_delete') }}",
            confirmButtonClass: 'btn btn-primary',
            cancelButtonClass: 'btn btn-danger ml-1',
            cancelButtonText: '{{ __('dashboard.action.cancel') }}',
            buttonsStyling: false,
        }).then(function (result) {
            if (result.value) {
                $.ajax({
                    url: url,
                    method: 'DELETE',
                    // _token: "{{ csrf_token() }}",
                    success: function (response) {
                        fireSuccess('{{ __('dashboard.alerts.deleted')  }}')
                        // Remove the raw
                        $('#row-' + rowId).remove();
                    }
                });
            }
        })
    }

    function swal_confirm_delete_selected(url, selectedItems) {
        if (selectedItems.length < 1)
            Swal.fire({
                type: 'error',
                title: '{{ __('dashboard.alerts.no_data_selected') }}',
                text: '{{ __('dashboard.alerts.select_data') }}',
                confirmButtonClass: 'btn btn-primary',
                buttonsStyling: false,
            })
        else {
            Swal.fire({
                title: '{{ __('dashboard.alerts.do_you_want_to_delete_selected_data') }}',
                // text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: '{{ __('dashboard.action.yes_delete_selected') }}',
                confirmButtonClass: 'btn btn-primary',
                cancelButtonClass: 'btn btn-danger ml-1',
                cancelButtonText: '{{ __('dashboard.action.cancel') }}',
                buttonsStyling: false,
            }).then(function (result) {
                if (result.value) {
                    $.ajax({
                        url,
                        method: 'POST',
                        data: {
                            ids: selectedItems
                        },
                        success: function () {
                            fireSuccess('{{ __('dashboard.alerts.deleted')  }}')

                            console.log(selectedItems);
                            selectedItems.forEach((element) => {
                                console.log('element : ' + element);
                                $('#row-' + element).remove();
                            });
                        }
                    });
                }
            })

        }
    }
</script>

resources/views/admin/includes/header.blade.php
<nav class="header-navbar navbar-expand-lg navbar navbar-with-menu floating-nav navbar-light navbar-shadow">
    <div class="navbar-wrapper">
        <div class="navbar-container content">
            <div class="navbar-collapse" id="navbar-mobile">
                <div class="mr-auto float-left bookmark-wrapper d-flex align-items-center">
                    <ul class="nav navbar-nav">

                        <li class="nav-item mobile-menu d-xl-none mr-auto">
                            <a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#">
                                <i class="ficon feather icon-menu"></i>
                            </a>
                        </li>

                    </ul>

                    <ul class="nav navbar-nav">
                        <li class="nav-item d-none d-lg-block">
                            {{--                            <a class="nav-link bookmark-star">--}}
                            {{--                                <i class="ficon feather icon-star warning"></i>--}}
                            {{--                            </a>--}}

                            <div class="bookmark-input search-input">
                                <div class="bookmark-input-icon">
                                    <i class="feather icon-search primary"></i>
                                </div>

                                <input class="form-control input" type="text" placeholder="Explore Vuexy..." tabindex="0" data-search="template-list">
                                <ul class="search-list search-list-bookmark"></ul>
                            </div>
                        </li>
                    </ul>
                </div>

                <ul class="nav navbar-nav float-right">
                    <li class="dropdown dropdown-language nav-item">
                        @if(!session()->has('them') || session()->get('them') == 'light')
                            <a class="dropdown-toggle nav-link" id="dropdown-flag" href="{{ route('admin.them', 'dark') }}" aria-haspopup="true" aria-expanded="false">
                                <i class="feather icon-moon"></i>
                                <span class="selected-language">الوضع الليلى</span>
                            </a>
                        @else
                            <a class="dropdown-toggle nav-link" id="dropdown-flag" href="{{ route('admin.them', 'light') }}" aria-haspopup="true" aria-expanded="false">
                                <i class="feather icon-sun"></i>
                                <span class="selected-language">الوضع النهارى</span>
                            </a>
                        @endif
                    </li>
                    <!-- Start Languages -->
                    <li class="dropdown dropdown-language nav-item">
                        <a class="dropdown-toggle nav-link" id="dropdown-flag" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="flag-icon @if(app()->getLocale() == 'ar' ) flag-icon-sa @else flag-icon-us @endif "></i>
                            <span class="selected-language">@if(app()->getLocale() == 'ar' ) العربية @else الإنجليزية @endif</span>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdown-flag">
                            <a class="dropdown-item" href="{{ route('admin.change.language', ['language' => (app()->getLocale() == 'ar') ? 'en' : 'ar']) }}" data-language="en">
                                <i class="flag-icon @if(app()->getLocale() == 'ar' ) flag-icon-us @else flag-icon-sa @endif "></i>
                                @if(app()->getLocale() == 'ar' ) الإنجليزية @elseالعربية@endif
                            </a>

                        </div>
                    </li>
                    <!-- End Languages -->

                    <!-- Start maximize -->
                    <li class="nav-item d-none d-lg-block">
                        <a class="nav-link nav-link-expand">
                            <i class="ficon feather icon-maximize"></i>
                        </a>
                    </li>
                    <!-- End maximize -->


                    <!-- Start notification -->
                    <li class="dropdown dropdown-notification nav-item">
                        <a class="nav-link nav-link-label" href="#" data-toggle="dropdown">
                            <i class="ficon feather icon-bell"></i>
                            <span class="badge badge-pill badge-primary badge-up @if(count($notifications) <1) hidden @endif">{{ count($notifications) }}</span>
                        </a>

                        <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
                            <li class="dropdown-menu-header">
                                <div class="dropdown-header m-0 p-2">
                                    @if(count($notifications) > 0)
                                    <h3 class="white">{{ __('notifications.new_notifications_count', ['count' => count($notifications)]) }}</h3>
                                    @else
                                        <h3 class="white">{{ __('notifications.no_new_notifications') }}</h3>
                                    @endif
                                </div>
                            </li>

                            <li class="scrollable-container media-list">

                                @foreach($notifications as $notification)
                                <a href="{{ $notification->url }}" class="d-flex justify-content-between">


                                    <div class="media d-flex align-items-start">
{{--                                        <div class="media-left">--}}
{{--                                            <i class="feather icon-message-circle font-medium-5 primary"></i>--}}
{{--                                        </div>--}}

                                        <div class="media-body">
                                            <h6 class="primary media-heading">{{ $notification->title }}</h6>
                                        </div>
                                        <small>
                                            <time class="media-meta" >{{ $notification->created_at->diffForHumans() }}</time>
                                        </small>
                                    </div>
                                </a>
                                @endforeach

                            </li>
                            <li class="dropdown-menu-footer"><a class="dropdown-item p-1 text-center" href="{{ route('admin.notifications.index') }}">عرض كل الاشعارات</a></li>
                        </ul>
                    </li>
                    <!-- End notification -->

                    <!-- Start Messages -->
                    <li class="dropdown dropdown-notification nav-item">
                        <a class="nav-link nav-link-label" href="#" data-toggle="dropdown">
                            <i class="ficon feather icon-message-square"></i>
                            <span class="badge badge-pill badge-success badge-up @if(count($messages) <1) hidden @endif">{{ count($messages) }}</span>
                        </a>

                        <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
                            <li class="dropdown-menu-header">
                                <div class="dropdown-header m-0 p-2">
                                    @if(count($notifications) > 0)
                                        <h3 class="white">{{ __('notifications.new_messages_count', ['count' => count($messages)]) }}</h3>
                                    @else
                                        <h3 class="white">{{ __('notifications.no_new_messages') }}</h3>
                                    @endif
                                </div>
                            </li>

                            <li class="scrollable-container media-list">

                                @foreach($messages as $message)
                                <a class="d-flex justify-content-between" href="{{ ($message['type'] == 'contact') ? route('admin.inbox.show', $message['data']) : route('admin.complains.show', $message['data']) }}">


                                    <div class="media d-flex align-items-start">
{{--                                        <div class="media-left">--}}
{{--                                            <i class="feather icon-message-circle font-medium-5 primary"></i>--}}
{{--                                        </div>--}}

                                        <div class="media-body">
                                            @if($message['type'] == 'contact')
                                            <h6 class="primary media-heading">{{ __('notifications.user_sent_message', ['name' => $message['data']->name]) }}</h6>
                                            @elseif($message['type'] == 'complain')
                                                <h6 class="primary media-heading">{{ __('notifications.user_sent_complain', ['name' => $message['data']->name]) }}</h6>
                                            @endif
{{--                                            <small class="notification-text"> Are your going to meet me tonight?</small>--}}
                                        </div>
                                        <small>
                                            <time class="media-meta" >{{ $message['data']->created_at->diffForHumans() }}</time>
                                        </small>
                                    </div>
                                </a>
                                @endforeach

                            </li>
                            <li class="dropdown-menu-footer"><a class="dropdown-item p-1 text-center" href="{{ route('admin.inbox.index') }}">عرض كل البريد الوارد</a></li>
                        </ul>
                    </li>
                    <!-- End Messages -->

                    <!-- Start user -->
                    <li class="dropdown dropdown-user nav-item">
                        <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
                            <div class="user-nav d-sm-flex d-none">
                                <span class="user-name text-bold-600">{{ auth()->user()->name }}</span>
{{--                                <span class="user-status">Available</span>--}}
                            </div>
                            <span>
                                <img class="round" src="{{ auth()->user()->avatarPath }}" alt="avatar" height="40" width="40">
                            </span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="{{ route('admin.settings.index') }}">
                                <i class="feather icon-settings"></i> الاعدادات
                            </a>

                            <a class="dropdown-item" href="{{ route('admin.inbox.index') }}">
                                <i class="feather icon-mail"></i> البريد الوارد
                            </a>

                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">
                                تسجيل الخروج
                            </a>
                            <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </div>
                    </li>
                    <!-- End user -->
                </ul>
            </div>
        </div>
    </div>
</nav>